version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "db_challenge"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db_volumes:/var/lib/mysql
volumes:
  db_volumes:
